import { Roboto } from "next/font/google";
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const getCurrentLanguage = () => {
//   // if (typeof window !== "undefined") {
//   const storedLanguage = localStorage.getItem("language");
//   return storedLanguage;
//   // }
// };

// console.log(getCurrentLanguage(), "globalglobal");
// console.log("reschedglobal");

// const globalLan = getCurrentLanguage();
// globalLan = "en" ? "globalLanEn" : "globalLanAr";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} `}>{children}</body>
    </html>
  );
}
